### ISSUE TITLE
Duplication issue with recipes that yield more than 1 item per craft

### ISSUE THREAD

**Issue by JasonMcRay** [jakimfett/Minechem#585]
Best to describe on example:
Gendustry labware can be crafted by using 4 glass panes and 1 diamond. This recipe will yield 7 labwares. When i put those labwares to decomposer, I am able to get 3 Carbon nanotubes (aka 1 diamond) from 1 labware. I know that this is not 100% chance to get, but i am mostly getting 6 Carbon Nanotubes per a cycle of 7 labwares. If this will get automated, someone can be able to create infinite diamonds pretty much.

This is happening for most of the items, where the crafting recipe will yield more than 1 itme. Maybe add a check for these recipes, and make the Decomposer only run when it has enough items in itself? So in the example above, the decomposer would be able only to start decomposing these labwares only if I put 7 of them.

**Comment by hilburn** [comment]
You should be getting a 1 in 7 output chance, so getting 6 carbon nanotubes rather than 3 (or 2 outputs instead of 1) is not a statistically significant deviation from expected results. If you did a bigger test, say 7 stacks of labware and got significantly more than 3 stacks of nanotubes then I would be pretty worried, but in all my testing to date I haven't found any such biases

**Comment by jakimfett** [comment]
Closing due to lack of additional user feedback or questions.
