### ISSUE TITLE
Synthesizer inconsistently picks target for 16 Fe or 16 Au

### ISSUE THREAD

**Issue by Euius** [jakimfett/Minechem#627]
NEI shows multiple possible outputs for a 16 Fe or 16 Au conversion, which one gets picked appears to be set at server boot and is random.  Normally the difference is entirely cosmetic and of no consequence, however with Mekanism installed one of the possible choices is "Iron Crystal" / "Gold Crystal" which requires a full x4 or x5 Mekanism ore processing setup (complete with brine tower) to turn into a useful ingot.

All the dusts have dictionary entries of "dustIron", while the crystal is instead registered as crystalIron

**Comment by jakimfett** [comment]
Oi, could I get you to look over the [Bug Reporting Guidelines](https://github.com/jakimfett/Minechem/wiki/Bug-Reporting) and update your bug report?

**Comment by Euius** [comment]
Minechem-1.7.10-5.0.5.358 currently, but also occurs in Minechem-1.7.10-5.0.5.323

Mekanism is MekanismGenerators-1.7.10-7.1.1.145

**Comment by jakimfett** [comment]
@Euius please go back and re-read the bug reporting guidelines, and then **follow** them.

**Comment by jakimfett** [comment]
Assuming that testing the latest build from Jenkins (like the bug reporting guidelines instructed) fixed the issue for @Euius. Please comment or open a new ticket if this isn't the case.

**Comment by Euius** [comment]
The bug is not fixed.  I will not reopen.  Your attitude toward bug reports exceeded my level of caring.

**Comment by jakimfett** [comment]
I've been thinking long and hard about your response over the past three days, @Euius. I wanted to give a response that addresses your complaint about my attitude, but holds you accountable for your own attitude as well.

First of all...when a bug is reported, I depend on whoever reported it to provide me with enough information that I can reproduce it. A bug that I can't reproduce is a bug that I can't fix. The bug reporting guidelines explain why, so I won't re-cap that here.

I created the bug reporting guidelines because I was tired of incomplete bug reports, or bug reports for problems that I've already fixed. They've been tweaked and updated as I find stuff that can make my life easier...and by extension, make it easier on whoever reported the bug. That's why I'm so specific in the guidelines about what I need people provide.

That out of the way...yeah, I was a bit snarky. I probably shouldn't have been. To be honest, it frustrates me when someone who is clearly an intelligent human being can't be bothered to follow a simple checklist.

It frustrates me because I've dumped hundreds of hours into making something fun and useful and (hopefully) awesome, and then I'm giving it away for free to anyone who would like to use it, with basically no restrictions. I've sunk huge amounts of my (extremely limited) free time into designing and coding and testing and balancing this mod, and it would take all of maybe....what, ten or twenty minutes for you to read through and understand the guidelines, grab the latest version, and then add a few more details? 

I always do my best to quickly fix bugs that get reported. I'm willing to work with someone to troubleshoot and understand and (hopefully) resolve almost any issue. But without you holding up your end of that partnership, I can't always fix things, or even find the issue in the first place.

I've given you hundreds of hours of my own time. I ask that you give me a few minutes of your time. If this is not acceptable to you, I'm not sure there's anything I can do to help you.
