### ISSUE TITLE
LegacyCraft compatability issue

### ISSUE THREAD

**Issue by Mortvana** [jakimfett/Minechem#706]
With JUST DragonAPI v4c, LegacyCraft v4a, and Minechem 5.0.5.393 (same with .387) I crash due an NPE, that only happens (300+ w/o LegacyCraft okay, but put LegacyCraft and Minechem together...)

https://gist.github.com/Mortvana/c49316e7e652f5c9c2ae

I have reported this to @ReikaKalseki too

**Comment by jakimfett** [comment]
Looks like this is due to LegacyCraft overriding the vanilla regeneration potion, and doing it in a way that results in a null potion item.
![](http://pics.jakimfett.com/2015-03-13_22-24-19.png)
You can prevent this from happening by setting 
``B:"Old Regen and Heal Potions"=false``
in the LegacyCraft config.

**Comment by ReikaKalseki** [comment]
I do override the regen potion, but why would that cause a null item?

**Comment by jakimfett** [comment]
@ReikaKalseki I'm not entirely certain. I'm planning on adding some null checks for the PharmacologyEffect and PharmacologyEffectRegistry so that null values in the potion registry won't cause Minechem to blow up, but I honestly don't know why a null potion would be left in the registry after a potion gets overridden.

**Comment by ReikaKalseki** [comment]
Perhaps a map key mismatch?

**Comment by jakimfett** [comment]
Nah, that particular bit of code just uses the unlocalized name to get the potion from the potionregistry.

**Comment by Mortvana** [comment]
@jakimfett Would make sense, I've had potion name weirdness in the past (since late 1.6.4) with LegacyCraft installed, I knew it was one of Reika's mods, but now I know it is LegacyCraft for sure.

**Comment by ReikaKalseki** [comment]
> Nah, that particular bit of code just uses the unlocalized name to get the potion from the potionregistry.

> Would make sense, I've had potion name weirdness in the past (since late 1.6.4) with LegacyCraft installed, I knew it was one of Reika's mods, but now I know it is LegacyCraft for sure.

Wait, is this related to that ".postfix" issue?

**Comment by Mortvana** [comment]
Yeah, and sometime the potion names showing up as a bunch of equals signs. I haven't actually been able to properly play with LegacyCraft since 1.6.4, so I can't say anything about 1.7.10 :P

**Comment by ReikaKalseki** [comment]
It might be fixed for v5.
