### ISSUE TITLE
crash with latest forge 1360 on startup

### ISSUE THREAD

**Issue by Too-DAMN-Much** [jakimfett/Minechem#718]
not sure this is a minechem issue but it's mentioned in the crash report so posting this here for now, this is the server side crash log:

http://paste.ubuntu.com/10789470/

the client here, never reaches the main menu screen:

http://paste.ubuntu.com/10789479/

at a guess this is probably because of cpw's change to the fluid registry in 1355, but other mods in the instance require FML 1355+ as well so i can't revert to a lower version.

**Comment by OscarBarrett** [comment]
I have the same issue on 1360. If I remove Minechem then I can start up my client/server.

**Comment by way2muchnoise** [comment]
This should be fixed in #719

**Comment by jakimfett** [comment]
Minechem builds below 395 are built against Forge 10.13.2.1291, because Forge versions later than this implement a bunch of changes to how fluids are handled.

To fix this, either update to Minechem build 395+ (which may be unstable, you have been warned...), or revert back to a supported version of Forge.
